#!/usr/bin/env python3
"""Deterministic verification of the anonymizer package (phase A).

Imports the REAL package from fable-director/anonymizer and runs the REAL CLI
against a throwaway HOME. No client data: every fixture is synthetic
(fable-director/anonymizer/corpus-public, generated by gen.py).

  A1  check digits: CF, P.IVA, IBAN, Luhn
  A2  rules: positives and negatives per category
  A3  span merge: longest wins, then engine priority; email never yields DOMINIO
  A4  columns: CSV ; TSV, JSON table, prose -> none, columns.extra
  A5  dictionary: exact, token with capital, ORG stems, whitelist
  A6  pmap: same normalized value -> same placeholder; chmod 600; tolerant restore
  A7  round-trip restore(redact(x)) == x on the public corpus
  A8  test --strict passes thresholds; report leaks no corpus value
  A9  CLI: STATUS on every command, scan writes no map, redact/restore --out, status --purge
  A10 performance <= 5 ms/KB on 200 KB
  A11 no catastrophic backtracking: seven pathological inputs, each under 1 s

Usage: python3 tests/anonymizer-verify.py   (exit 0 = all green)
"""
import json
import os
import stat
import subprocess
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
PLUGIN = HERE.parent / "fable-director"
SCRIPT = PLUGIN / "scripts" / "anonymizer.py"
FIXTURES = PLUGIN / "anonymizer" / "corpus-public"
sys.path.insert(0, str(PLUGIN))

passed, failed = [], []


def check(name, ok, evidence=""):
    (passed if ok else failed).append(name)
    print(f"{'PASS' if ok else 'FAIL'}  {name}" + ("" if ok else f"\n      {evidence}"))


def field(out, key):
    for line in out.splitlines():
        if line.startswith(key + ":"):
            return line.split(":", 1)[1].strip()
    return None


def run(home, args, stdin=None, cwd=None):
    env = dict(os.environ, HOME=str(home))
    return subprocess.run([sys.executable, str(SCRIPT)] + args, input=stdin,
                          capture_output=True, text=True, env=env,
                          cwd=str(cwd or home), timeout=120)


# ---------------------------------------------------------------- A1 / A2
def _cats(spans):
    return sorted((s.cat, s.value) for s in spans)


def test_rules():
    from anonymizer.rules.base import cf_ok, piva_ok, iban_ok, luhn_ok
    from anonymizer.rules import find_spans
    from anonymizer.config import DEFAULTS
    import copy
    cfg = copy.deepcopy(DEFAULTS)

    check("A1 CF check digit", cf_ok("RSSMRA80A01H501U") and not cf_ok("RSSMRA80A01H501A"))
    check("A1 P.IVA check digit", piva_ok("04739200790") and not piva_ok("04739200791"))
    check("A1 IBAN mod 97", iban_ok("IT60X0542811101000000123456") and not iban_ok("IT60X0542811101000000123457")
          and iban_ok("DE89370400440532013000"))
    check("A1 Luhn", luhn_ok("4539578763621486") and not luhn_ok("4539578763621487"))

    def spans(text, **over):
        c = copy.deepcopy(cfg)
        c["rules"].update(over)
        return find_spans(text, c, [])

    r = spans("scrivi a Mario.Rossi@Example.it oggi")
    check("A2 EMAIL found, no DOMINIO from its host",
          _cats(r) == [("EMAIL", "Mario.Rossi@Example.it")], _cats(r))

    r = spans("il fatturato 2024 è di 1331234567 euro; ordine n. 0961123456; cell 3331234567")
    check("A2 TEL: bare fixed number ignored by default, mobile format always taken",
          [v for c, v in _cats(r) if c == "TEL"] == ["3331234567"], _cats(r))
    r = spans("tel. 0962 123456, cell 333 1234567, +39 06 12345678, whatsapp: 3471234567, 0039 320 1234567")
    check("A2 TEL with context, +39, 0039", [v for c, v in _cats(r) if c == "TEL"] ==
          sorted(["0962 123456", "333 1234567", "+39 06 12345678", "3471234567", "0039 320 1234567"]), _cats(r))
    r = spans("fisso 0962 123456", tel_requires_context=False)
    check("A2 TEL without context when tel_requires_context=false", ("TEL", "0962 123456") in _cats(r), _cats(r))
    r = spans("call +44 20 7946 0958 or +1 415 555 2671")
    check("A2 TEL foreign with + prefix", len([1 for c, v in _cats(r) if c == "TEL"]) == 2, _cats(r))

    r = spans("sede in Via Roma 12, 88900 Crotone (KR) e via SGR 2 non conta")
    check("A2 INDIRIZZO with CAP included, ANSI-like 'via SGR 2' excluded",
          _cats(r) == [("INDIRIZZO", "Via Roma 12, 88900 Crotone (KR)")], _cats(r))
    r = spans("residente in piazza Giuseppe Garibaldi n. 3 a Catanzaro")
    check("A2 INDIRIZZO with n. and no CAP", _cats(r) == [("INDIRIZZO", "piazza Giuseppe Garibaldi n. 3")], _cats(r))

    r = spans("server 127.0.0.1, 0.0.0.0, 192.168.1.10, 10.0.0.5, 172.16.3.4, 169.254.1.1 e 8.8.8.8")
    check("A2 IP: loopback/private/link-local excluded, public kept", _cats(r) == [("IP", "8.8.8.8")], _cats(r))

    r = spans("vedi https://github.com/frsorrentino/x e https://img.shields.io/badge e https://cliente-finale.it/p?q=1")
    check("A2 URL domain-only, whitelist hosts skipped", _cats(r) == [("DOMINIO", "cliente-finale.it")], _cats(r))
    r = spans("vedi https://cliente-finale.it/p?q=1", url="full")
    check("A2 URL full mode", _cats(r) == [("URL", "https://cliente-finale.it/p?q=1")], _cats(r))
    r = spans("vedi https://cliente-finale.it/p", url="off")
    check("A2 URL off", _cats(r) == [], _cats(r))

    r = spans("CF RSSMRA80A01H501U e RSSMRA80A01H501A")
    check("A2 CF valid only", _cats(r) == [("CF", "RSSMRA80A01H501U")], _cats(r))
    r = spans("P.IVA 04739200790, IT04739200790, prot. n. 04739200790, pezzi 04739200791")
    check("A2 PIVA with context/IT prefix, not after prot., check digit enforced",
          [v for c, v in _cats(r) if c == "PIVA"] == ["04739200790", "04739200790"], _cats(r))
    r = spans("IBAN IT60 X054 2811 1010 0000 0123 456 e IT60X0542811101000000123457 e DE89 3704 0044 0532 0130 00")
    check("A2 IBAN it spaced + generic, invalid dropped",
          [v for c, v in _cats(r) if c == "IBAN"] == ["DE89 3704 0044 0532 0130 00", "IT60 X054 2811 1010 0000 0123 456"], _cats(r))
    r = spans("carta 4539 5787 6362 1486 e 4539 5787 6362 1487")
    check("A2 CARTA Luhn", [v for c, v in _cats(r) if c == "CARTA"] == ["4539 5787 6362 1486"], _cats(r))
    r = spans("targa FA 123 BC, EX123YZ, IO 123 QU")
    check("A2 TARGA format, IOQU excluded", [v for c, v in _cats(r) if c == "TARGA"] == ["EX123YZ", "FA 123 BC"], _cats(r))
    r = spans("nato a Crotone il 12/03/1985, data di nascita: 1985-03-12, riunione del 12/03/2026")
    check("A2 DATA_NASCITA only with context", [v for c, v in _cats(r) if c == "DATA_NASCITA"] == ["12/03/1985", "1985-03-12"], _cats(r))
    r = spans("prot. n. 12345/2026 e R.G. 4567/2025 e fascicolo n. 88")
    check("A2 PROTOCOLLO", [v for c, v in _cats(r) if c == "PROTOCOLLO"] == ["12345/2026", "4567/2025", "88"], _cats(r))

    from anonymizer.spans import Span
    taken = [Span(9, 31, "EMAIL", "Mario.Rossi@Example.it", "columns")]
    r = find_spans("scrivi a Mario.Rossi@Example.it oggi", cfg, taken)
    check("A2 rules skip regions already taken", r == [], r)
    r = spans("contatta Pixelfarm su https://pixelfarm.it e info@pixelfarm.it")
    check("A2 non-whitelisted host: DOMINIO and EMAIL both redacted",
          _cats(r) == [("DOMINIO", "pixelfarm.it"), ("EMAIL", "info@pixelfarm.it")], _cats(r))
    c = copy.deepcopy(cfg); c["whitelist"] = ["pixelfarm.it"]
    r = find_spans("contatta https://pixelfarm.it e info@pixelfarm.it", c, [])
    check("A2 whitelisted host: domain skipped, e-mail still redacted",
          _cats(r) == [("EMAIL", "info@pixelfarm.it")], _cats(r))


# ---------------------------------------------------------------- A4
def test_columns():
    import copy
    from anonymizer.config import DEFAULTS
    from anonymizer.columns import find_spans, detect
    cfg = copy.deepcopy(DEFAULTS)

    brevo = "\ufeffEMAIL;NOME;COGNOME;PHONE;BIRTHDAY;NOTE\nanna@esempio.it;Anna;Verdi;+39 333 1111111;1990-01-02;chiamare lunedi\n;;;;;\nb@esempio.it;\"Bianchi, Luca\";;;;\n"
    check("A4 detect csv ;", detect(brevo) == ("csv", ";"), detect(brevo))
    r = find_spans(brevo, cfg, [])
    check("A4 brevo cells whole, empty skipped, quoted cell inner, NOTE free",
          _cats(r) == [("DATA_NASCITA", "1990-01-02"), ("EMAIL", "anna@esempio.it"), ("EMAIL", "b@esempio.it"),
                       ("PERSONA", "Anna"), ("PERSONA", "Bianchi, Luca"), ("PERSONA", "Verdi"), ("TEL", "+39 333 1111111")],
          _cats(r))
    check("A4 offsets exact", all(brevo[s.start:s.end] == s.value for s in r), [(s, brevo[s.start:s.end]) for s in r])

    tsv = "Customer e-mail*\tLastname*\tFirstname*\tCompany\tVAT number\n" + "x@y.it\tRossi\tMario\tACME Srl\t04739200790\n" + "z@y.it\tNeri\tPia\t\t\n"
    r = find_spans(tsv, cfg, [])
    check("A4 prestashop tsv with * headers",
          _cats(r) == [("EMAIL", "x@y.it"), ("EMAIL", "z@y.it"), ("ORG", "ACME Srl"), ("PERSONA", "Mario"),
                       ("PERSONA", "Neri"), ("PERSONA", "Pia"), ("PERSONA", "Rossi"), ("PIVA", "04739200790")], _cats(r))

    pix = "cliente,vat,email,pec,domini\nOrtensia Web,04739200790,a@ortensiaweb.example,,ortensiaweb.example | ortensiaweb.test\n"
    r = find_spans(pix, cfg, [])
    check("A4 pixelbox multi-value domini split",
          _cats(r) == [("DOMINIO", "ortensiaweb.example"), ("DOMINIO", "ortensiaweb.test"), ("EMAIL", "a@ortensiaweb.example"),
                       ("ORG", "Ortensia Web"), ("PIVA", "04739200790")], _cats(r))

    raw = "id_customer;firstname;lastname;email;passwd;secure_key;birthday;note\n7;Ugo;Blu;u@b.it;$2y$10$abc;deadbeef;1980-05-05;\n"
    r = find_spans(raw, cfg, [])
    check("A4 prestashop raw: passwd/secure_key -> SECRET, id ignored",
          [c for c, v in _cats(r)] == ["DATA_NASCITA", "EMAIL", "PERSONA", "PERSONA", "SECRET", "SECRET"], _cats(r))

    js = json.dumps([{"email": "j@k.it", "first_name": "Jo", "age": 3, "note": "x"}, {"email": "l@m.it", "first_name": "Al"}], indent=1, ensure_ascii=False)
    check("A4 detect json table", detect(js) == ("json",), detect(js))
    r = find_spans(js, cfg, [])
    check("A4 json table values with exact offsets",
          _cats(r) == [("EMAIL", "j@k.it"), ("EMAIL", "l@m.it"), ("PERSONA", "Al"), ("PERSONA", "Jo")]
          and all(js[s.start:s.end] == s.value for s in r), _cats(r))

    prose = "Gentile cliente, la sua pratica; è pronta, ritiri; entro, venerdì.\nAltro; testo, qui\n"
    check("A4 prose is not a table", detect(prose) is None and find_spans(prose, cfg, []) == [], detect(prose))

    c = copy.deepcopy(cfg); c["columns"]["extra"] = {"e": "EMAIL", "referente": "PERSONA"}
    ex = "e,referente,r\nq@w.it,Gia Neri,4\n"
    r = find_spans(ex, c, [])
    check("A4 columns.extra headers", _cats(r) == [("EMAIL", "q@w.it"), ("PERSONA", "Gia Neri")], _cats(r))

    c = copy.deepcopy(cfg); c["whitelist"] = ["ortensiaweb.example"]
    r = find_spans(pix, c, [])
    check("A4 whitelisted value skipped in cells", ("DOMINIO", "ortensiaweb.example") not in _cats(r), _cats(r))

    multi = "email,note\na@b.it,\"riga uno\nriga due\"\nc@d.it,x\n"
    r = find_spans(multi, cfg, [])
    check("A4 multiline quoted cell: doc skipped (no spans)", r == [], _cats(r))


# ---------------------------------------------------------------- A5 + engine
def test_dictionary_and_engine(home):
    import copy
    from anonymizer.config import DEFAULTS, load
    from anonymizer.dictionary import find_spans, stems
    from anonymizer import engine
    from anonymizer.pmap import PlaceholderMap
    cfg = copy.deepcopy(DEFAULTS)
    cfg["dictionary"].update({"PERSONA": ["Mario Rossi", "Anna Verdi"], "ORG": ["Ortensia Web S.r.l.s.", "Officine Zampolini SRL"],
                              "DOMINIO": ["ortensiaweb.example"]})
    cfg["whitelist"] += ["Rossini"]

    check("A5 stems", stems("Ortensia Web S.r.l.s.") == ["ortensia web s.r.l.s.", "ortensia web"]
          and stems("Officine Zampolini SRL") == ["officine zampolini srl", "officine zampolini"], stems("Ortensia Web S.r.l.s."))

    t = "Ho sentito MARIO ROSSI e la sig.ra Verdi; Rossi ha firmato. I rossi sono colori. Rossini no."
    r = find_spans(t, cfg, [])
    check("A5 exact casefold + token with capital, lowercase token ignored, whitelist",
          _cats(r) == [("PERSONA", "MARIO ROSSI"), ("PERSONA", "Rossi"), ("PERSONA", "Verdi")], _cats(r))
    t = "Fattura a Ortensia Web srls e a ortensia web per il sito ortensiaweb.example; officine zampolini paga."
    r = find_spans(t, cfg, [])
    check("A5 ORG stems and DOMINIO", _cats(r) == [("DOMINIO", "ortensiaweb.example"), ("ORG", "Ortensia Web"), ("ORG", "officine zampolini"),
                                                   ("ORG", "ortensia web")], _cats(r))

    text = "Cliente Mario Rossi, mail mario@ortensiaweb.example, tel 333 1234567, CF RSSMRA80A01H501U, sito https://ortensiaweb.example/x"
    pm = PlaceholderMap()
    out, rep = engine.redact(text, pm, cfg)
    check("A6/engine redact replaces every category once",
          out == "Cliente [PERSONA_1], mail [EMAIL_1], tel [TEL_1], CF [CF_1], sito https://[DOMINIO_1]/x", out)
    check("engine report has counts only",
          rep["counts"] == {"PERSONA": 1, "EMAIL": 1, "TEL": 1, "CF": 1, "DOMINIO": 1} and set(rep["by_engine"]) <= {"rules", "dictionary", "columns"}
          and "Rossi" not in json.dumps(rep), rep)
    back, info = engine.restore(out, pm)
    check("engine restore round-trip", back == text and info["restored"] == 5, back)
    rep2 = engine.scan(text, cfg)
    check("engine scan same counts, map untouched", rep2["counts"] == rep["counts"] and pm.counts() == {"PERSONA": 1, "EMAIL": 1, "TEL": 1, "CF": 1, "DOMINIO": 1}, rep2)
    out2, _ = engine.redact("Rossi e mario@ortensiaweb.example di nuovo", pm, cfg)
    check("engine placeholders stable across calls (surname alone is its own value)", out2 == "[PERSONA_2] e [EMAIL_1] di nuovo", out2)

    proj = home / "proj" / "sub"
    proj.mkdir(parents=True)
    (home / "proj" / ".git").mkdir()
    (home / "proj" / ".fd-anonymizer.json").write_text(json.dumps({"dictionary": {"PERSONA": ["Pia Neri"]}, "whitelist": ["Crotone"],
                                                                     "columns": {"extra": {"ref": "PERSONA"}}, "guard": "deny"}))
    (home / ".claude" / "fable-director").mkdir(parents=True, exist_ok=True)
    (home / ".claude" / "fable-director" / "anonymizer.json").write_text(json.dumps({"rules": {"url": "full"}, "whitelist": ["x.it"]}))
    c = load(cwd=proj, home=home)
    check("config merge default <- global <- project (found upwards to .git)",
          c["rules"]["url"] == "full" and c["guard"] == "deny" and "Crotone" in c["whitelist"] and "x.it" in c["whitelist"]
          and "github.com" in c["whitelist"] and c["dictionary"]["PERSONA"] == ["Pia Neri"] and c["columns"]["extra"] == {"ref": "PERSONA"}
          and c["rules"]["tel_requires_context"] is True and len(c["_sources"]) == 2, c)


# ---------------------------------------------------------------- A7
def test_corpus():
    import copy
    from anonymizer import corpus
    from anonymizer.config import DEFAULTS, _merge
    docs = corpus.load(FIXTURES)
    check("A7 public corpus loads with annotations", len(docs) >= 8 and all(d.spans for d in docs), [d.id for d in docs])
    cfg = _merge(copy.deepcopy(DEFAULTS), corpus.config_override(FIXTURES))
    bad = corpus.validate(docs)
    check("A7 annotations match document text", bad == [], bad)
    m = corpus.evaluate(docs, cfg)
    formatted = m["formatted"]
    check("A7 formatted categories recall >= 0.99 precision >= 0.90",
          formatted["recall"] >= 0.99 and formatted["precision"] >= 0.90,
          {k: v for k, v in m["per_category"].items() if v["fp"] or v["fn"]})
    check("A7 PERSONA reported but informative", "PERSONA" in m["per_category"] and "PERSONA" not in corpus.FORMATTED)
    failed_rt = corpus.roundtrip(docs, cfg)
    check("A7 round-trip restore(redact(x)) == x on every doc", failed_rt == [], failed_rt)
    check("A7 metrics carry no values", "@" not in json.dumps(m) and not any(d.text[:20] in json.dumps(m) for d in docs))


# ---------------------------------------------------------------- A8 / A9 / A10
def test_cli(home):
    from anonymizer.pmap import map_path
    r = run(home, ["test", "--strict", "--json"])
    check("A8 test --strict on public corpus passes", r.returncode == 0 and field(r.stdout, "STATUS") == "ok", r.stdout[-800:] + r.stderr[-800:])
    values = []
    for f in (FIXTURES / "docs").glob("*.spans.json"):
        values += [s["text"] for s in json.loads(f.read_text())["spans"]]
    leaked = [v for v in values if v in r.stdout]
    check("A8 test report leaks no corpus value", leaked == [], leaked[:5])
    check("A8 test report names public corpus only (no private dir in throwaway HOME)", "public" in r.stdout and "private" not in field(r.stdout, "DETAIL"), field(r.stdout, "DETAIL"))

    src = FIXTURES / "docs" / "email-thread.txt"
    maps_dir = map_path("x", home).parent
    before = sorted(p.name for p in maps_dir.glob("*")) if maps_dir.is_dir() else []
    r = run(home, ["scan", str(src), str(FIXTURES / "docs" / "export-brevo.txt")])
    check("A9 scan prints STATUS ok and counts", r.returncode == 0 and field(r.stdout, "STATUS") == "ok" and "EMAIL" in r.stdout, r.stdout)
    after = sorted(p.name for p in maps_dir.glob("*")) if maps_dir.is_dir() else []
    check("A9 scan writes no map", before == after, (before, after))
    r = run(home, ["scan", str(src), "--json"])
    check("A9 scan --json is parseable and value-free", '"counts"' in r.stdout and "@" not in r.stdout.split("STATUS:")[0], r.stdout[:300])

    out = home / "red.txt"
    r = run(home, ["redact", str(src), "--map", "sess1", "--out", str(out)])
    red = out.read_text()
    check("A9 redact --out writes placeholders and the map", r.returncode == 0 and field(r.stdout, "STATUS") == "ok"
          and "[EMAIL_1]" in red and "@" not in red and map_path("sess1", home).is_file(), r.stdout + r.stderr)
    back = home / "back.txt"
    r = run(home, ["restore", str(out), "--map", "sess1", "--out", str(back)])
    check("A9 restore --out round-trips", r.returncode == 0 and back.read_text() == src.read_text(), r.stdout + r.stderr)
    r = run(home, ["redact", "--stdin", "--map", "sess1"], stdin="scrivi a " + json.loads((FIXTURES / "docs" / "email-thread.spans.json").read_text())["spans"][1]["text"] + " subito\n")
    check("A9 redact --stdin reuses the map and prints text on stdout, STATUS on stderr",
          r.stdout == "scrivi a [EMAIL_1] subito\n" and field(r.stderr, "STATUS") == "ok", r.stdout + r.stderr)
    r = run(home, ["restore", "--stdin", "--map", "nope"], stdin="x")
    check("A9 restore with missing map is an error", r.returncode == 1 and field(r.stderr, "STATUS") == "error", r.stdout + r.stderr)
    r = run(home, ["redact", str(home / "missing.txt")])
    check("A9 redact missing file is an error (STATUS on stderr without --out)", r.returncode == 1 and field(r.stderr, "STATUS") == "error", r.stdout + r.stderr)
    binp = home / "bin.dat"; binp.write_bytes(b"\x00\x01\xff\xfe" * 100)
    r = run(home, ["scan", str(binp)])
    check("A9 binary file refused", r.returncode == 1 and "not text" in r.stdout, r.stdout)

    old = map_path("old", home)
    d = json.loads(map_path("sess1", home).read_text()); d["created"] = "2020-01-01T00:00:00+00:00"
    old.write_text(json.dumps(d))
    r = run(home, ["status"])
    check("A9 status lists maps and flags expired", field(r.stdout, "STATUS") == "ok" and "sess1" in r.stdout and "old" in r.stdout and "expired" in r.stdout, r.stdout)
    r = run(home, ["status", "--purge"])
    check("A9 status --purge removes expired map only", not old.exists() and map_path("sess1", home).exists() and field(r.stdout, "STATUS") == "ok", r.stdout)
    r = run(home, ["frobnicate"])
    check("A9 unknown command is an error with usage", r.returncode != 0 and ("usage" in (r.stdout + r.stderr).lower()), r.stdout + r.stderr)

    big = home / "big.txt"
    big.write_text(src.read_text() * (200_000 // len(src.read_text()) + 1))
    t0 = time.perf_counter(); r = run(home, ["scan", str(big), "--json"]); wall = time.perf_counter() - t0
    rep = json.loads(r.stdout.split("STATUS:")[0])
    ms_kb = rep[0]["ms"] / (rep[0]["chars"] / 1024)
    check("A10 scan <= 5 ms/KB on 200 KB", ms_kb <= 5.0, f"{ms_kb:.2f} ms/KB, wall {wall:.2f}s")

    # A11 — ReDoS: every rule must stay linear-ish on adversarial input
    # (nested quantifiers in the address, CAP, phone and e-mail rules).
    import copy
    from anonymizer.rules import find_spans
    from anonymizer.config import DEFAULTS
    cfg = copy.deepcopy(DEFAULTS)
    cases = {"via+parole": "via " + "Aaaa " * 3000 + "!", "prot cifre": "prot. n. " + "1" * 5000 + "x",
             "tel separatori": "tel. 3" + " 3" * 4000 + "x", "cap comune": "88900 " + "Aaaa " * 3000 + "?",
             "iban-like": "IT" + "12" * 3000 + "!", "nato il": "nato a " + "a" * 3000 + " il x",
             "email-like": "a" * 5000 + "@" + "b" * 5000 + "!"}
    slow = {}
    for name, text in cases.items():
        t0 = time.perf_counter()
        find_spans(text, cfg, [])
        ms = (time.perf_counter() - t0) * 1000
        if ms > 1000:
            slow[name] = round(ms)
    check("A11 no catastrophic backtracking (each pathological input < 1 s)", not slow, slow)


# ---------------------------------------------------------------- A3 / A6
def test_spans_and_pmap(home):
    from anonymizer.spans import Span, merge_spans, apply_spans
    from anonymizer.pmap import PlaceholderMap, normalize, map_path

    long = Span(0, 30, "INDIRIZZO", "Via Roma 12, 88900 Crotone (KR)", "rules")
    short = Span(13, 18, "CAP_COMUNE", "88900", "rules")
    merged = merge_spans([short, long])
    check("A3 longest span wins on overlap", merged == [long], repr(merged))

    a = Span(5, 15, "EMAIL", "x@y.it", "rules")
    b = Span(5, 15, "EMAIL", "x@y.it", "columns")
    merged = merge_spans([a, b])
    check("A3 equal length: columns beats rules", merged == [b], repr(merged))

    text = "mail x@y.it e tel +39 333 1234567 fine"
    spans = [Span(5, 11, "EMAIL", "x@y.it", "rules"),
             Span(18, 33, "TEL", "+39 333 1234567", "rules")]
    pm = PlaceholderMap()
    out = apply_spans(text, merge_spans(spans), pm.placeholder_for)
    check("A3 apply_spans replaces right-to-left with stable offsets",
          out == "mail [EMAIL_1] e tel [TEL_1] fine", out)

    check("A6 normalize email is case-insensitive",
          normalize("EMAIL", "A@B.it") == normalize("EMAIL", "a@b.IT"))
    check("A6 normalize tel strips separators and maps 0039 to +39",
          normalize("TEL", "0039 333-123.4567") == normalize("TEL", "+39 3331234567"))
    check("A6 normalize iban drops spaces and upcases",
          normalize("IBAN", "it60 x054 2811") == normalize("IBAN", "IT60X0542811"))
    check("A6 normalize person casefolds and squeezes spaces",
          normalize("PERSONA", "Mario  ROSSI") == normalize("PERSONA", "mario rossi"))

    pm = PlaceholderMap()
    p1 = pm.placeholder("EMAIL", "A@b.it")
    p2 = pm.placeholder("EMAIL", "a@B.IT")
    p3 = pm.placeholder("EMAIL", "c@d.it")
    check("A6 same normalized value -> same number, other surface form -> variant letter",
          p1 == "[EMAIL_1]" and p2 == "[EMAIL_1B]" and p3 == "[EMAIL_2]" and pm.lookup("EMAIL", 1) == "A@b.it",
          f"{p1} {p2} {p3} {pm.lookup('EMAIL', 1)}")

    path = map_path("t1", home=home)
    pm.save(path)
    mode = stat.S_IMODE(path.stat().st_mode)
    dmode = stat.S_IMODE(path.parent.stat().st_mode)
    check("A6 map saved chmod 600 in chmod 700 dir", mode == 0o600 and dmode == 0o700,
          f"{oct(mode)} {oct(dmode)}")
    pm2 = PlaceholderMap.load(path)
    check("A6 map reload keeps entries and counts",
          pm2.lookup("EMAIL", 2) == "c@d.it" and pm2.counts() == {"EMAIL": 2},
          f"{pm2.counts()}")
    p4 = pm2.placeholder("EMAIL", "a@b.it")
    check("A6 reloaded map reuses number, third form gets C", p4 == "[EMAIL_1C]", p4)

    restored, info = pm2.restore("x [email_1] y EMAIL_2 z [EMAIL_9] w [TEL_1]")
    check("A6 restore tolerant of brackets/case, unknown kept and counted",
          restored == "x A@b.it y c@d.it z [EMAIL_9] w [TEL_1]"
          and info == {"restored": 2, "unknown": 2}, f"{restored} {info}")

    p5 = pm2.placeholder("ORG", "Ortensia Web Srl"); p6 = pm2.placeholder("ORG", "ORTENSIA WEB SRL"); p7 = pm2.placeholder("ORG", "Ortensia Web Srl")
    check("A6 same entity, second surface form -> variant letter", (p5, p6, p7) == ("[ORG_1]", "[ORG_1B]", "[ORG_1]"), (p5, p6, p7))
    restored, info = pm2.restore("[ORG_1] vs [ORG_1B] vs org_1b")
    check("A6 restore returns the exact surface form per variant", restored == "Ortensia Web Srl vs ORTENSIA WEB SRL vs ORTENSIA WEB SRL", restored)
    (path).write_text("{not json")
    try:
        PlaceholderMap.load(path)
        check("A6 corrupt map raises", False, "no exception")
    except ValueError:
        check("A6 corrupt map raises", True)


def main():
    home = Path(tempfile.mkdtemp(prefix="fd-anon-home-"))
    test_spans_and_pmap(home)
    test_rules()
    test_columns()
    test_dictionary_and_engine(home)
    test_corpus()
    test_cli(home)
    print(f"\n{len(passed)} passed, {len(failed)} failed")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
